from __future__ import annotations

from typing import Protocol, Sequence

from app.storage.models import DemandSnapshot, StockSnapshot, SupplyOperation


class SnapshotRepository(Protocol):
    def replace_stocks(self, snapshots: Sequence[StockSnapshot]) -> None: ...
    def replace_demand(self, snapshots: Sequence[DemandSnapshot]) -> None: ...
    def latest_stocks(self) -> list[StockSnapshot]: ...
    def latest_demand(self) -> list[DemandSnapshot]: ...


class OperationRepository(Protocol):
    def add(self, operation: SupplyOperation) -> None: ...
    def get(self, operation_id: str) -> SupplyOperation | None: ...
    def get_by_key(self, key: str) -> SupplyOperation | None: ...
    def save(self, operation: SupplyOperation) -> None: ...
    def unfinished(self) -> list[SupplyOperation]: ...


class AuditRepository(Protocol):
    def record(self, actor: str, action: str, result: str, details: str = "") -> None: ...

